# This is a basic workflow to help you get started with Actions

name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2

    # Standard usage
    - uses: bwilczek/jekyll-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'
        cname: zielonekowale.pl
